// <auto-generated />
using System;
using BackendQuizletclone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendQuizletclone.Migrations
{
    [DbContext(typeof(QuizletCloneDbContext))]
    partial class QuizletCloneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendQuizletclone.Data.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Example")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsStarred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("StudySetId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Flashcar__3214EC071539970A");

                    b.HasIndex("StudySetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.StudyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(2.5);

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<int?>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsStarred")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudyPro__3214EC073EE2B5A4");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("UserId");

                    b.ToTable("StudyProgresses");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.StudySet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudySet__3214EC07C3A4FD02");

                    b.HasIndex("UserId");

                    b.ToTable("StudySets");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC078F2F0EEB");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E40DBCD2A0")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D3BD4728")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.Flashcard", b =>
                {
                    b.HasOne("BackendQuizletclone.Data.StudySet", "StudySet")
                        .WithMany("Flashcards")
                        .HasForeignKey("StudySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Flashcards_StudySets");

                    b.Navigation("StudySet");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.StudyProgress", b =>
                {
                    b.HasOne("BackendQuizletclone.Data.Flashcard", "Flashcard")
                        .WithMany("StudyProgresses")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Flashcards");

                    b.HasOne("BackendQuizletclone.Data.User", "User")
                        .WithMany("StudyProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Users");

                    b.Navigation("Flashcard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.StudySet", b =>
                {
                    b.HasOne("BackendQuizletclone.Data.User", "User")
                        .WithMany("StudySets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudySets_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.Flashcard", b =>
                {
                    b.Navigation("StudyProgresses");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.StudySet", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("BackendQuizletclone.Data.User", b =>
                {
                    b.Navigation("StudyProgresses");

                    b.Navigation("StudySets");
                });
#pragma warning restore 612, 618
        }
    }
}
